#!/bin/bash
set -e

mkdir piuroot; cd piuroot

wget https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-minirootfs-3.18.2-x86_64.tar.gz -O root.tar.gz
tar xpvf root.tar.gz --xattrs-include='*.*' --numeric-owner

cd ..

echo "------------------------------------------------"
echo "piu-gendir finished..."
echo "now use piu-copy"
echo "(init=/piu-init)"
