#!/bin/bash
set -e

mkdir piuroot; cd piuroot

wget https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-root.tar.xz -O root.tar.gz
set +e
tar xpvf root.tar.gz --xattrs-include='*.*' --numeric-owner
set -e

cd ..

echo "------------------------------------------------"
echo "piu-gendir finished..."
echo "now use piu-copy"
echo "(init=/piu-init)"
