#!/bin/bash
set -e

pattern="/boot/vmlinuz*"
files=( $pattern )

initrdp="/boot/initrd*"
irdfiles=( $pattern )

#qemu-img create temp.img 500M
#mkfs.ext4 ./temp.img

qemu-system-x86_64 -m 2G -nographic -kernel ${files[0]} -initrd ${irdfiles[0]} -append "console=ttyS0 root=/dev/sda rw init=/piu-init" -hda piu-packed.img
