#!/bin/bash
set -e

mkdir piuroot; cd piuroot

wget https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-root.tar.xz -O root.tar.gz
set +e
tar xpvf root.tar.gz --xattrs-include='*.*' --numeric-owner
set -e

echo "test:x:1000:1000::/home/test:/bin/bash" >> ./etc/passwd
echo "test:x:1000:" >> ./etc/group
echo "test:$(openssl passwd -6 password):::::::" >> ./etc/shadow
mkdir ./home/test

cd ..

echo "------------------------------------------------"
echo "piu-gendir finished..."
echo "now use piu-copy"
echo "(init=/piu-init)"
