#!/bin/bash
set -e

if [ -z "$1" ]
	then
	echo "No argument supplied"
	exit
fi

basep=$(dirname "$0")

$basep/piu-gendir
$basep/piu-copy $1
echo "Requires password for piu-pack"
sudo $basep/piu-pack
$basep/piu-qemu
$basep/piu-clean

