#!/bin/bash

mkdir -p rootfs/{bin,sbin,etc,proc,sys,dev,usr/bin,usr/sbin}
cp init rootfs/init

wget https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox

cp busybox rootfs/bin
chmod +x rootfs/bin/busybox
rootfs/bin/busybox --install -s rootfs/bin

cd rootfs
find . -print0 | cpio --null -ov --format=newc | gzip -9 >../initramfs.cpio.gz
cd ..

