#!/bin/bash

if [[ -f "initramfs.cpio.gz" ]]; then
	echo "deleting initramfs"
	rm initramfs.cpio.gz
fi

if [[ -d "rootfs" ]]; then
	echo "deleting rootfs"
	rm -rf rootfs
fi

mkdir -p rootfs/{bin,sbin,etc,proc,sys,dev,usr/bin,usr/sbin}
cp init rootfs/init

if [[ -f "busybox" ]]; then
	echo "using current busybox"
else
	wget https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox
fi

cp busybox rootfs/bin
chmod +x rootfs/bin/busybox
rootfs/bin/busybox --install -s rootfs/bin

cd rootfs
find . -print0 | cpio --null -ov --format=newc | gzip -9 >../initramfs.cpio.gz
cd ..

